[package]
name = "tarjetas_refrigerio"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.13.0"
tokio = { version = "1.52.3", features = ["fs"] }

dotenvy = "0.15.7"
futures = "0.3.32"
thiserror = "2.0.18"
mongodb = "3.7.0"

diesel = { version = "2.3.9", features = ["serde_json","chrono", "numeric"] }
diesel-async = { version = "0.9.0", features = ["postgres", "bb8"] }
rust_decimal = {version = "1.42.0", features = ["db-diesel-postgres", "serde-float", "macros"]}

bb8 = "0.9.1"

serde = {version = "1.0.228", features=["derive"]}
serde_json={version="1.0.150"}
chrono = {version = "0.4.44", features=["serde"]}

tracing = "0.1.44"
tracing-subscriber = {version = "0.3.23", features = ["env-filter","fmt","time","chrono"]}
tracing-log = "0.2.0"
tracing-appender = "0.2.5"
log="0.4.30"


jsonwebtoken = {version="10.4.0",features = ["rust_crypto"]}
aes-gcm = "0.10.3"
base64 = "0.22.1"
sha3 = "0.12.0"
urlencoding = "2.1.3"
rand = "0.10.1"

uuid = {version="1.23.1", features=["v4","macro-diagnostics"]}
bcrypt = "0.19.1"
